#ifndef AWS_CLIENT_CREDENTIAL_KEYS_H
#define AWS_CLIENT_CREDENTIAL_KEYS_H

#include <stdint.h>

/*
 * PEM-encoded client certificate.
 *
 * Must include the PEM header and footer:
 * "-----BEGIN CERTIFICATE-----\n"\
 * "...base64 data...\n"\
 * "-----END CERTIFICATE-----"
 */

/*
//MIO
#define keyCLIENT_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIIDWjCCAkKgAwIBAgIVAONI2X+MQ6PD1gXDWjJkOCeveIilMA0GCSqGSIb3DQEB\n"\
"CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t\n"\
"IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0xODExMTgxODAw\n"\
"MTBaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh\n"\
"dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJCGXs6kI7RkFV4BYd\n"\
"2XFjHQFJ3dcaxC+rPC/7wGEOFuyvY0T9SOYdhLei6nYWfJ78ohB20c43LGmcUdu0\n"\
"/vcyPBs7lqwq/beSvJOyrVwpYjR9uZ+eoWq0d2s5R/nktwKm4e5KghgDW408fOtR\n"\
"ODeMxvVxX0+PEYY6imrE3jRViDG6yY+hPlWFtcfacQ2rSVHFBq88xF6eIVzGjsWI\n"\
"HcYco3fuRnB08WxVy44reTRwX3D6SWl/xFLi+OHrO6lucSXQHctkobDKUPtOVKS5\n"\
"ftkemuxQCXRUJ2ZCTmEndofllUd3qbWml732ThQ5abA5H2j5qwjp8e3rzepzbbzP\n"\
"2efXAgMBAAGjYDBeMB8GA1UdIwQYMBaAFGvH/qcLBAIY4YUCfTRUEoa1acDTMB0G\n"\
"A1UdDgQWBBTrUkbnIutw8Rir51DW3qVGNHOeezAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"\
"DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAXEqhMP32AJRgXbYCZv/xpJd6\n"\
"ojJxkSN4J8RDVFVgpeCMeFX6k1AvQ4aV/+lliti2O0YJH77oxEsYP+GGZA8Dis2V\n"\
"66Pn7QhWDHB6lWyXZp2k2QyyS7JJPb4mVorUgsB5yxIHgVxLVXPooG8qaZKkogZ9\n"\
"KGohwtYMvEXdQw3UjLYx3XFak0Giruqg38cn7o+R48QVBZyAS8PoUojUMh3oPhWH\n"\
"FD6rsBOm7Qjq4n/UtfQtjEz/U400/TKfd+xqpAYqM8zU6t+gTzk+OuFincNFNVvS\n"\
"Ay/WMxuASvaK3fHz6kz6QWR5Oiwg2N7m5ZT2nnWBH+K77Ez0hl6MZgYdtvF0TQ==\n"\
"-----END CERTIFICATE-----"
*/

#define keyCLIENT_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIID6DCCAtACFFoNG6p8JMNMjI/Y+MryEfCQEzFNMA0GCSqGSIb3DQEBCwUAMIGU\n"\
"MQswCQYDVQQGEwJDTzESMBAGA1UECAwJQW50aW9xdWlhMREwDwYDVQQHDAhNZWRl\n"\
"bGxpbjESMBAGA1UECgwJQWN1YW1hdGljMRIwEAYDVQQLDAlBY3VhbWF0aWMxEjAQ\n"\
"BgNVBAMMCUFjdWFtYXRpYzEiMCAGCSqGSIb3DQEJARYTYWN1YW1hdGljQGdtYWls\n"\
"LmNvbTAeFw0xODEyMDIwMjI3MjVaFw0xOTEyMDIwMjI3MjVaMIHLMQswCQYDVQQG\n"\
"EwJDTzESMBAGA1UECAwJQW50aW9xdWlhMREwDwYDVQQHDAhNZWRlbGxpbjESMBAG\n"\
"A1UECgwJQWN1YW1hdGljMRIwEAYDVQQLDAlBY3VhbWF0aWMxSTBHBgNVBAMMQDA2\n"\
"ODlhMjY1ZTkzOTE0YTYyZWFhYzM0YmE1MzUzNTI1ZjEyNzM2YWNjNzUzOThjYjU4\n"\
"NjIwMDlmNTVmMmJlZjgxIjAgBgkqhkiG9w0BCQEWE2FjdWFtYXRpY0BnbWFpbC5j\n"\
"b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCs4Oy2KgXfuaA5L0BS\n"\
"gT3GmBPyY1HW8dTH3Ocd77Wem60W8OkB38ud4sLZpkTbTxlcAeUPN2OMgdNabc7a\n"\
"hG8wA7Vju7Elh914xKQ6sYj5pm2/22POvy65vsuUc+QaSixSzxUKiZyL+lXyE00Y\n"\
"bvTmYxSiQb2IFap3BqcMOYAx5pPe5F5NgJWg4N4Gd26XbZUlFVZe/JJYGvRKAGS0\n"\
"9m6jdx105iZBI7T5KwVqwcpwOH5Nbz6W8mVR6AwHuKg1RSHmJD6l4iRIwExJDLwp\n"\
"F7ocYJL7FJ9pYWH9OFiYVPUP63uK42MpKh3irRhg/dt5/EnpUercoRftk31bJKBM\n"\
"+qfvAgMBAAEwDQYJKoZIhvcNAQELBQADggEBACFv3qXZPOQX4pL4PvRlYwYo8rhk\n"\
"Fog8kGKyIzUa/dBTZbd8s+K1ECW0gh/xG7hLC5vOd2vTCZ1949094p7wGpu7TEAH\n"\
"7Fwfz5vHD+8KJ912h61f9Uesw11vAB8EGSEEl6qgExxToVJedG2GDaMzgWdCssEy\n"\
"sgVeWWG3WJCawdQ+08ZjGslWDKT0SN027I/wl40UeM0fVyN9Q7iy2j0CEMeNyB+7\n"\
"CKloYqdFNpDzlW+yJ9oNwcOxP7ZmJVBpjmrqFtWW6U4I6XPgNgmGwAuBYiAQdj0e\n"\
"MppZI0KUBHRac0ZxK3s3kV4FPpqm+men8HqY4wbVK777CH1wtPkOUXuGMis=\n"\
"-----END CERTIFICATE-----"




/*
 * PEM-encoded client private key.
 *
 * Must include the PEM header and footer:
 * "-----BEGIN RSA PRIVATE KEY-----\n"\
 * "...base64 data...\n"\
 * "-----END RSA PRIVATE KEY-----"
 */


/*
//MIO
#define keyCLIENT_PRIVATE_KEY_PEM \
"-----BEGIN RSA PRIVATE KEY-----\n"\
"MIIEpAIBAAKCAQEAyQhl7OpCO0ZBVeAWHdlxYx0BSd3XGsQvqzwv+8BhDhbsr2NE\n"\
"/UjmHYS3oup2Fnye/KIQdtHONyxpnFHbtP73MjwbO5asKv23kryTsq1cKWI0fbmf\n"\
"nqFqtHdrOUf55LcCpuHuSoIYA1uNPHzrUTg3jMb1cV9PjxGGOopqxN40VYgxusmP\n"\
"oT5VhbXH2nENq0lRxQavPMReniFcxo7FiB3GHKN37kZwdPFsVcuOK3k0cF9w+klp\n"\
"f8RS4vjh6zupbnEl0B3LZKGwylD7TlSkuX7ZHprsUAl0VCdmQk5hJ3aH5ZVHd6m1\n"\
"ppe99k4UOWmwOR9o+asI6fHt683qc228z9nn1wIDAQABAoIBAHrhOkQdUMygffE6\n"\
"3unx7p/xq8b15bTDtIuLZ50Pk4OkOZpfKF1VwOrMI99eRz4pgJjVixDF37HT4N4f\n"\
"Hxe8PWckXFUJHUXN/fagc/tkgg/9qi4rV0kES4/x6sWBnFrUDrfpI9nBOWJcBLGz\n"\
"fbcQkMvpFT/uTVgbExwXXXnmhMC+PyvEIPe5EOhB2G4PkCpRuFrYHncic9k9cBXI\n"\
"p4daRwIA6U3gNFeKWnwNsVDp7z/YVZ0/qUbVIHYzic8ZBFhh6YJr5JbvjOKU0V3J\n"\
"51EKbiKcNlSrjd8bhLjo/NAAD3mBRSFoBBB26aPn8Qw+tHjIqNPV00O9iDMdZzXB\n"\
"5QBkHTECgYEA+6WgYCxZTTzhRRtfpcYwn2i3uoIhznvYCSjLOpqRVoegw8UYugJR\n"\
"Cc3lPoHRgakR4xcPrIbLL4HWFgJ56mNN8JGInSELEZ/o1y9wgAIRlz+/fDD525ut\n"\
"QTC2o/oiMZz10xFhlerxA7VdRs5j8+Ndke0mZPLTrJl52fz3HTRyGs8CgYEAzIKi\n"\
"yXODmqIJqCAb4OhWVFoEf1bGxAcA1HLlxMM3+coKQWTWdFN8uAwCx2E966fycoG0\n"\
"IIjXc5xqNgvSsPTE1SqcEDQvqhLSMwuQejQdaY/n4x7Whnim58yvXd/gYij/X4YK\n"\
"vU8H5UNt4qpfra2jt6R4EdDO2KVwuVUnsEqABHkCgYEAkrqnQYx6YYve+hGU+q8O\n"\
"CNThVDGujpwtgmGz5i7cEa0xcxUIbuUM5X+VbJX7V/QCBvyaWgmajc/RybGV7rIK\n"\
"bvwcwSnUL2mjNV1m5mzOXvd/qmVQOtmR8xH5XLFroKwZtgFLekOsVnI4uiF7rGhl\n"\
"VcIGghQIknpGz3EtkWzUH4cCgYEAh1WXtiosF+NM8qY07LOzlWRwf3gEVuqvgOd7\n"\
"56asXy91c+rwA9DPwten6xsNp+nfBimQ8sq7kPUcUCGozpNbwhjNZ+ew9yI3WbI4\n"\
"bLYaFKY3dNQOcLRc9x47mqqxSSQKQsNoTfiDqBLkH9BROpSit78t+dQtXa61lt+k\n"\
"QQQ8DTkCgYBHvuCKJOwInOeimwlMJ9czLkl9t+xXFpUL/DNHCANjV2MyDP+0R5ao\n"\
"mUHEQHLv6dUHmtl/QW0qWBU/qj1z7cAS4PrUE7Luflf9Tgub8cpVMOBaEvB/InKs\n"\
"rc7QmkPCzh8GUmEie4z07mHcURbDci6vpod33in6vRMqcfrIY/t/ww==\n"\
"-----END RSA PRIVATE KEY-----"
*/

#define keyCLIENT_PRIVATE_KEY_PEM \
"-----BEGIN RSA PRIVATE KEY-----\n"\
"MIIEowIBAAKCAQEArODstioF37mgOS9AUoE9xpgT8mNR1vHUx9znHe+1nputFvDp\n"\
"Ad/LneLC2aZE208ZXAHlDzdjjIHTWm3O2oRvMAO1Y7uxJYfdeMSkOrGI+aZtv9tj\n"\
"zr8uub7LlHPkGkosUs8VComci/pV8hNNGG705mMUokG9iBWqdwanDDmAMeaT3uRe\n"\
"TYCVoODeBndul22VJRVWXvySWBr0SgBktPZuo3cddOYmQSO0+SsFasHKcDh+TW8+\n"\
"lvJlUegMB7ioNUUh5iQ+peIkSMBMSQy8KRe6HGCS+xSfaWFh/ThYmFT1D+t7iuNj\n"\
"KSod4q0YYP3befxJ6VHq3KEX7ZN9WySgTPqn7wIDAQABAoIBAHtnu9F1QegoG4V2\n"\
"g1Xhx/VBjcuStlLXIerhd2FZQa5MtkwQAGREGpdDzY+MLs7WMeYJvDcWdMtRyUtd\n"\
"4zD9JFmD7DGbQ6Lkz2VsCUeUf5CmCuXPd/mXY4VX+v6nk4ZouCcMh5qUDNmnAz7g\n"\
"JEJywgLLa2k/wEmqHZsFdq01RptXLW2bRy8Axlhi1J91mjz52Up0xSisU/1K3GiC\n"\
"cv7nGrAggxalqgLp9yJpOjYCagmbnmmas4o6U+JK8I0jxZ84kt22iIUgneqG7nHW\n"\
"9F5TnzBplhMpgK6osFllfWdH+Omnuk50yYCXdJ+YVEzpc+QgASGkterDtHrtNPjT\n"\
"ACSdSRECgYEA5ZFMNyEJj98Rs4Gf19yoMj6vSsJBhFYRV5jghidUX23klJXnak5P\n"\
"pemDx5Itsu5mQ+NosfjeA6v/09mLSNZG9UaVJpFrz6Ccasj1szCqsNRBEj7RqVeQ\n"\
"JcdSoIVebrZgeG/3EIdNhpgat29wJYdBkG6QIHEF0ub/L9r31iFMnysCgYEAwMir\n"\
"xZ/43sRPH0yhbTx7vXlZNa97MM1eWFkBr/0L2ZufRzhoEfqqJwyWPdbYiagpR5hv\n"\
"QkRpvG2mAyS6/+XWZuaJW6Fon2PEFx+j9Ch7lYA92VZF8F3fjk3KMIYRhgYDEnsj\n"\
"4G5aKP/ANBCX2g5U6bw3WME/lO1arl6FaXqoWE0CgYAl0EAYmJWFoD2/LqvQl6UQ\n"\
"2ahwDP1TugWTQzhAgLvyGBzdqK98oDeYYZV2SwrB/WjU5+F350FSo4M5Nw0tSzZW\n"\
"8nBg8PUsNw1svXtTL8H97IhnY/ePCEBTKLjgffdnDx1m2TJ+A3tunyFPc8iqNdRD\n"\
"4SJWZaeK7Me97ziBieygDwKBgAfc52yjDrJ/TT7YkEj1S5K5zVKsOpkN90ghMTlt\n"\
"V7tjZoawHUaGc8Qt9j7FcYWDz1M1O2x3f9yImFnOeLYROMJvqrCLD8pYdln/F1/Q\n"\
"+uFpHpyrsSSRn5mdQJ7kCPjva9aoIRl5RsIfVEaLWrYxGXODErrS/vXjDGzKPCTG\n"\
"NPGNAoGBANIjq2LOboXbFR/pGNR2Y2YRFwJMh+f3YsH/xtykNw/BhpCbuabcaqQJ\n"\
"LsQrLsQNZbshn1HYK37ST3fgmCKnqFXt7G3ObxUv+bpIuVoIYb2UGoneVz6tOSJ+\n"\
"Fs0wr57lFz59QPVpJY/ibi1oX5cazhMwCDSj66ajExdFSajPe3bh\n"\
"-----END RSA PRIVATE KEY-----"

/*
 * PEM-encoded Just-in-Time Registration (JITR) certificate (optional).
 *
 * If used, must include the PEM header and footer:
 * "-----BEGIN CERTIFICATE-----\n"\
 * "...base64 data...\n"\
 * "-----END CERTIFICATE-----"
 */

#define keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM  NULL


/* The constants above are set to const char * pointers defined in aws_dev_mode_key_provisioning.c,
 * and externed here for use in C files.  NOTE!  THIS IS DONE FOR CONVENIENCE
 * DURING AN EVALUATION PHASE AND IS NOT GOOD PRACTICE FOR PRODUCTION SYSTEMS
 * WHICH MUST STORE KEYS SECURELY. */
//extern const char clientcredentialCLIENT_CERTIFICATE_PEM[];
//extern const char* clientcredentialJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM;
//extern const char clientcredentialCLIENT_PRIVATE_KEY_PEM[];
//extern const uint32_t clientcredentialCLIENT_CERTIFICATE_LENGTH;
//extern const uint32_t clientcredentialCLIENT_PRIVATE_KEY_LENGTH;

#endif /* AWS_CLIENT_CREDENTIAL_KEYS_H */
